# Generated by Django 2.0.3 on 2018-03-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('roleid', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], max_length=100)),
            ],
        ),
    ]
