# Generated by Django 2.2.6 on 2020-02-24 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(verbose_name='Size of Spring')),
                ('length', models.FloatField(verbose_name='Length of Spring')),
                ('received', models.DateTimeField(auto_now_add=True, verbose_name='Received Date')),
                ('finished', models.DateTimeField(null=True, verbose_name='Finished Date')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpringConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date Used')),
                ('length', models.FloatField(verbose_name='Length Used')),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='springs.Spring')),
            ],
        ),
    ]
