# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'costs',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itemid', models.TextField(primary_key=True, serialize=False)),
                ('include', models.NullBooleanField()),
                ('itemindex', models.IntegerField(blank=True, null=True)),
                ('item', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unitsize', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='itemid',
            field=models.ForeignKey(db_column='itemid', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Items'),
        ),
        migrations.AddField(
            model_name='costs',
            name='itemid',
            field=models.ForeignKey(db_column='itemid', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.Items'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('itemid', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='costs',
            unique_together=set([('itemid', 'date')]),
        ),
    ]
