# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_sums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='notes',
            new_name='usernotes',
        ),
        migrations.AddField(
            model_name='items',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
