# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170731_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='itemindex',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
