# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_items_sublocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static\\inventory\\images'),
        ),
    ]
