# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='costs',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
