# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170816_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
