# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='include',
        ),
    ]
