# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 14:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_items_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
