# Generated by Django 2.0.3 on 2018-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20170817_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteelCoil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Weight of Coil')),
                ('width', models.FloatField(verbose_name='Width of Coil')),
                ('recieved', models.DateTimeField(auto_now=True, verbose_name='Recieved Date')),
                ('opened', models.DateTimeField(verbose_name='Opened Date')),
                ('finished', models.DateTimeField(verbose_name='Finished Date')),
            ],
        ),
    ]
