# Generated by Django 2.0.3 on 2018-09-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180920_0945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SteelCoil',
        ),
    ]
