# Generated by Django 2.0.3 on 2018-03-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessoryid', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('motorcover', 'Motor Cover'), ('gearcover', 'Gear Cover'), ('facia', 'Facia'), ('foc', 'FrontofMotorClip'), ('chainplate', 'Chain Plate'), ('slidelocks', 'Slide Locks'), ('pinlocks', 'Pin Locks'), ('feederslat', 'Feeder Slat'), ('', 'Other')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BottomBar',
            fields=[
                ('bottombarid', models.AutoField(primary_key=True, serialize=False)),
                ('slat_type', models.CharField(choices=[('BRD', 'BRD Slats'), ('NY', 'New York Slats'), ('CRN', 'Crown Slats'), ('MCR', 'Mini Crown Slats')], max_length=50)),
                ('face', models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior')], max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('angle', models.CharField(choices=[('D', 'Double Angle'), ('S', 'Single Angle')], max_length=50)),
                ('bottom_rubber', models.CharField(max_length=50)),
                ('slope_height', models.CharField(max_length=50)),
                ('slope_side', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('doorid', models.AutoField(primary_key=True, serialize=False)),
                ('open_width', models.CharField(max_length=50)),
                ('open_height', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('hoodid', models.AutoField(primary_key=True, serialize=False)),
                ('custom', models.BooleanField()),
                ('width', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('origin_date', models.DateField()),
                ('due_date', models.DateField()),
                ('customer_po', models.CharField(max_length=50)),
                ('work_order', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('pipeid', models.AutoField(primary_key=True, serialize=False)),
                ('pipelength', models.CharField(max_length=50)),
                ('pipediameter', models.CharField(max_length=50)),
                ('shaftlength', models.CharField(max_length=50)),
                ('shaftdiameter', models.CharField(max_length=50)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door')),
            ],
        ),
        migrations.CreateModel(
            name='Slats',
            fields=[
                ('slatid', models.AutoField(primary_key=True, serialize=False)),
                ('slat_type', models.CharField(choices=[('BRD', 'BRD Slats'), ('NY', 'New York Slats'), ('CRN', 'Crown Slats'), ('MCR', 'Mini Crown Slats')], max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('assemble', models.CharField(choices=[('A', 'Assembled'), ('U', 'Unassembled')], max_length=50)),
                ('face', models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior')], max_length=50)),
                ('enclocks', models.CharField(choices=[('FLSTP', 'Flat Stamped'), ('FLCST', 'Flat Cast'), ('FLCWD', 'Flat Cast Windlock'), ('CRCST', 'Curved Cast'), ('CRCWD', 'Curved Cast Windlock'), ('MNCST', 'Mini Cast')], max_length=50)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door')),
            ],
        ),
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('springid', models.AutoField(primary_key=True, serialize=False)),
                ('spring_type', models.CharField(choices=[('I', 'Inner'), ('O', 'Outer')], max_length=50)),
                ('outer_diameter', models.DecimalField(decimal_places=4, max_digits=4)),
                ('wire_diameter', models.DecimalField(decimal_places=10, max_digits=10)),
                ('stretch', models.CharField(max_length=50)),
                ('pipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.Pipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('trackid', models.AutoField(primary_key=True, serialize=False)),
                ('bracket_size', models.CharField(max_length=50)),
                ('wall_angle_height', models.CharField(max_length=50)),
                ('inner_angle_height', models.CharField(max_length=50)),
                ('outer_angle_height', models.CharField(max_length=50)),
                ('hole_patter', models.TextField()),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAccessory',
            fields=[
                ('accessory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Accessory')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('doors.accessory',),
        ),
        migrations.CreateModel(
            name='Facia',
            fields=[
                ('accessory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Accessory')),
                ('length', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
            ],
            bases=('doors.accessory',),
        ),
        migrations.CreateModel(
            name='FeederSlat',
            fields=[
                ('accessory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Accessory')),
                ('face', models.CharField(choices=[('I', 'Interior'), ('E', 'Exterior')], max_length=50)),
                ('slattype', models.CharField(choices=[('BRD', 'BRD Slats'), ('NY', 'New York Slats'), ('CRN', 'Crown Slats'), ('MCR', 'Mini Crown Slats')], max_length=50)),
                ('length', models.CharField(max_length=50)),
            ],
            bases=('doors.accessory',),
        ),
        migrations.CreateModel(
            name='GearCover',
            fields=[
                ('accessory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Accessory')),
                ('hand', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], max_length=50)),
            ],
            bases=('doors.accessory',),
        ),
        migrations.CreateModel(
            name='MotorCover',
            fields=[
                ('accessory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Accessory')),
                ('hand', models.CharField(choices=[('R', 'Right'), ('L', 'Left')], max_length=50)),
            ],
            bases=('doors.accessory',),
        ),
        migrations.AddField(
            model_name='door',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Order'),
        ),
        migrations.AddField(
            model_name='bottombar',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='door',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
    ]
