# Generated by Django 2.0.3 on 2018-04-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0004_door_hand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slats',
            old_name='enclocks',
            new_name='endlocks',
        ),
    ]
