# Generated by Django 2.0.3 on 2018-04-12 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0005_auto_20180412_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endlocks',
            fields=[
                ('endlockid', models.AutoField(primary_key=True, serialize=False)),
                ('endlock_type', models.CharField(choices=[('FLSTP', 'Flat Stamped'), ('FLCST', 'Flat Cast'), ('FLCWD', 'Flat Cast Windlock'), ('CRCST', 'Curved Cast'), ('CRCWD', 'Curved Cast Windlock'), ('MNCST', 'Mini Cast')], max_length=50)),
                ('continuous', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='slats',
            name='endlocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doors.Endlocks'),
        ),
    ]
