# Generated by Django 2.0.3 on 2018-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0007_auto_20180412_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='baffle',
            field=models.BooleanField(default=False),
        ),
    ]
