# Generated by Django 2.0.3 on 2018-04-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0008_hood_baffle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='hole_patter',
            new_name='hole_pattern',
        ),
    ]
