# Generated by Django 2.0.3 on 2018-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0009_auto_20180413_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='weatherstripping',
            field=models.BooleanField(default=False),
        ),
    ]
