# Generated by Django 2.0.3 on 2018-04-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0011_auto_20180413_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryBrackets',
            fields=[
                ('brackets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='doors.Brackets')),
                ('type', models.CharField(choices=[('D', 'Drive'), ('C', 'Charge')], max_length=50)),
            ],
            bases=('doors.brackets',),
        ),
    ]
