# Generated by Django 2.0.3 on 2018-04-16 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0014_auto_20180416_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='door',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AlterField(
            model_name='bottombar',
            name='door',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AlterField(
            model_name='door',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Order'),
        ),
        migrations.AlterField(
            model_name='hood',
            name='door',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Company'),
        ),
        migrations.AlterField(
            model_name='slats',
            name='door',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AlterField(
            model_name='slats',
            name='endlocks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doors.Endlocks'),
        ),
        migrations.AlterField(
            model_name='spring',
            name='pipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='doors.Pipe'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='brackets',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Brackets'),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='door',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
    ]
