# Generated by Django 2.0.3 on 2018-05-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0015_auto_20180416_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessorybrackets',
            name='door',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='kind',
            field=models.CharField(blank=True, choices=[('motorcover', 'Motor Cover'), ('gearcover', 'Gear Cover'), ('facia', 'Facia'), ('foc', 'FrontofMotorClip'), ('chainplate', 'Chain Plate'), ('slidelocks', 'Slide Locks'), ('pinlocks', 'Pin Locks'), ('feederslat', 'Feeder Slat'), ('hardware', 'Hardware'), ('', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bottombar',
            name='slope_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bottombar',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brackets',
            name='bracket_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brackets',
            name='hand',
            field=models.CharField(blank=True, choices=[('R', 'Right'), ('L', 'Left')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facia',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facia',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feederslat',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hood',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hood',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slats',
            name='endlocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doors.Endlocks'),
        ),
        migrations.AlterField(
            model_name='slats',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slats',
            name='width',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='spring',
            name='outer_diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='spring',
            name='wire_diameter',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='brackets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Brackets'),
        ),
    ]
