# Generated by Django 2.0.3 on 2018-05-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0016_auto_20180509_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='hole_pattern',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='inner_angle_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='outer_angle_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='wall_angle_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
