# Generated by Django 2.0.3 on 2018-05-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0018_auto_20180509_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='endlocks',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endlocks',
            name='windlocks',
            field=models.BooleanField(default=False),
        ),
    ]
