# Generated by Django 2.0.3 on 2018-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0019_auto_20180522_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='cycles',
            field=models.CharField(choices=[(12500, 12500), (25000, 25000), (50000, 50000), (100000, 100000), (16500, 16500)], default=12500, max_length=50),
            preserve_default=False,
        ),
    ]
