# Generated by Django 2.0.3 on 2018-06-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0020_pipe_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipe',
            name='cycles',
            field=models.CharField(choices=[('12500', '12500'), ('25000', '25000'), ('50000', '50000'), ('100000', '100000'), ('16500', '16500')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doors.Door'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='pipediameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='pipelength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='shaftdiameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='shaftlength',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
