# Generated by Django 2.0.3 on 2018-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0022_auto_20180910_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='spring',
            name='coiledlength',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
