# Generated by Django 2.0.3 on 2018-09-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0023_spring_coiledlength'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spring',
            old_name='coiledlength',
            new_name='uncoiledlength',
        ),
    ]
